version: '2'
services:
  graphql-engine:
    image: hasura/graphql-engine:latest
    network_mode: "host"
    ports:
      - '8080:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
      HASURA_GRAPHQL_ACCESS_KEY: Xjb84POExBxidM5gB3tdVrWHK1nqbx9o
    command:
      - graphql-engine
      - serve
      - --enable-console
