version: '2.1'
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
  timescale:
    image: timescale/timescaledb:latest-pg12
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    restart: always
    environment:
      PORT: 3000
      RABBITMQ_HOST: rabbit
      RABBITMQ_USER: root
      RABBITMQ_PASSWORD: password
      POSTGRES_HOST: timescale
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - timescale
      - rabbit
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - '8080:8080'
    depends_on:
      - timescale
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@timescale:5432/postgres
      HASURA_GRAPHQL_ACCESS_KEY: Xjb84POExBxidM5gB3tdVrWHK1nqbx9o
    command: graphql-engine serve --enable-console

volumes:
  db_data:
